{"cards": [
            {  
   "file":"images/10_Random_Rewards.png",
   "name":"IMAGES_10_Random_Rewards_PNG",
   "type":"png"
},
{  
   "file":"images/11_Fixed_Reward_Schedule.png",
   "name":"IMAGES_11_Fixed_Reward_Schedule_PNG",
   "type":"png"
},
{  
   "file":"images/12_Time_Dependant.png",
   "name":"IMAGES_12_Time_Dependant_PNG",
   "type":"png"
},
{  
   "file":"images/13_On-Boarding.png",
   "name":"IMAGES_13_On-Boarding_PNG",
   "type":"png"
},
{  
   "file":"images/14_Signposting.png",
   "name":"IMAGES_Signposting_PNG",
   "type":"png"
},
{  
   "file":"images/15_Loss_Aversion.png",
   "name":"IMAGES_15_Loss_Aversion_PNG",
   "type":"png"
},
{  
   "file":"images/16_Progress.png",
   "name":"IMAGES_16_Progress_PNG",
   "type":"png"
},
{  
   "file":"images/17_Theme.png",
   "name":"IMAGES_17_Theme_PNG",
   "type":"png"
},
{  
   "file":"images/18_Narrative.png",
   "name":"IMAGES_18_Narrative_PNG",
   "type":"png"
},
{  
   "file":"images/19_Meaning.png",
   "name":"IMAGES_19_Meaning_PNG",
   "type":"png"
},

{  
   "file":"images/20_Care_Taking.png",
   "name":"IMAGES_20_Care_Taking_PNG",
   "type":"png"
},
{  
   "file":"images/21_Access.png",
   "name":"IMAGES_21_Access_PNG",
   "type":"png"
},
{  
   "file":"images/22_Collect.png",
   "name":"IMAGES_22_Collect_PNG",
   "type":"png"
},
{  
   "file":"images/23_Gifting.png",
   "name":"IMAGES_23_Gifting_PNG",
   "type":"png"
},
{  
   "file":"images/24_Knowledge.png",
   "name":"IMAGES_24_Knowledge_PNG",
   "type":"png"
},
{  
   "file":"images/25_Innovation.png",
   "name":"IMAGES_25_Innovation_PNG",
   "type":"png"
},
{  
   "file":"images/26_Voting.png",
   "name":"IMAGES_26_Voting_PNG",
   "type":"png"
},
{  
   "file":"images/27_Development_Tools.png",
   "name":"IMAGES_27_Development_Tools_PNG",
   "type":"png"
},
{  
   "file":"images/28_Anonymity.png",
   "name":"IMAGES_28_Anonymity_PNG",
   "type":"png"
},
{  
   "file":"images/29_Light_Touch.png",
   "name":"IMAGES_29_Light_Touch_PNG",
   "type":"png"
},
{  
   "file":"images/30_Anarchy.png",
   "name":"IMAGES_30_Anarchy_PNG",
   "type":"png"
},
{  
   "file":"images/31_Exploration.png",
   "name":"IMAGES_31_Exploration_PNG",
   "type":"png"
},
{  
   "file":"images/32_Choices.png",
   "name":"IMAGES_32_Choices_PNG",
   "type":"png"
},
{  
   "file":"images/33_Easter_Eggs.png",
   "name":"IMAGES_33_Easter_Eggs_PNG",
   "type":"png"
},
{  
   "file":"images/34_Unlockables.png",
   "name":"IMAGES_34_Unlockables_PNG",
   "type":"png"
},
{  
   "file":"images/35_Creativity_Tools.png",
   "name":"IMAGES_35_Creativity_Tools_PNG",
   "type":"png"
},
{  
   "file":"images/36_Customisation.png",
   "name":"IMAGES_36_Customisation_PNG",
   "type":"png"
},
{  
   "file":"images/37_Challenges.png",
   "name":"IMAGES_37_Challenges_PNG",
   "type":"png"
},
{  
   "file":"images/38_Certificates.png",
   "name":"IMAGES_38_Certificates_PNG",
   "type":"png"
},
{  
   "file":"images/39_Learning.png",
   "name":"IMAGES_39_Learning_PNG",
   "type":"png"
},
{  
   "file":"images/3_General.png",
   "name":"IMAGES_3_General_PNG",
   "type":"png"
},
{  
   "file":"images/40_Quests.png",
   "name":"IMAGES_40_Quests_PNG",
   "type":"png"
},
{  
   "file":"images/41_Levels.png",
   "name":"IMAGES_41_Levels_PNG",
   "type":"png"
},
{  
   "file":"images/42_Boss_Battles.png",
   "name":"IMAGES_42_Boss_Battles_PNG",
   "type":"png"
},
{  
   "file":"images/43_Points.png",
   "name":"IMAGES_43_Points_PNG",
   "type":"png"
},
{  
   "file":"images/44_Prizes.png",
   "name":"IMAGES_44_Prizes_PNG",
   "type":"png"
},
{  
   "file":"images/45_Leaderboards.png",
   "name":"IMAGES_45_Leaderboards_PNG",
   "type":"png"
},
{  
   "file":"images/46_Badges.png",
   "name":"IMAGES_46_Badges_PNG",
   "type":"png"
},
{  
   "file":"images/47_Virtual_ Economy.png",
   "name":"IMAGES_47_Virtual_ Economy_PNG",
   "type":"png"
},
{  
   "file":"images/48_Lottery.png",
   "name":"IMAGES_48_Lottery_PNG",
   "type":"png"
},
{  
   "file":"images/49_Guilds.png",
   "name":"IMAGES_49_Guilds_PNG",
   "type":"png"
},
{  
   "file":"images/4_Philanthropists.png",
   "name":"IMAGES_4_Philanthropists_PNG",
   "type":"png"
},
{  
   "file":"images/50_Social_Network.png",
   "name":"IMAGES_50_Social_Network_PNG",
   "type":"png"
},
{  
   "file":"images/51_Social_Status.png",
   "name":"IMAGES_51_Social_Status_PNG",
   "type":"png"
},
{  
   "file":"images/52_Social_Discovery.png",
   "name":"IMAGES_52_Social_Discovery_PNG",
   "type":"png"
},
{  
   "file":"images/53_Social_Pressure.png",
   "name":"IMAGES_53_Social_Pressure_PNG",
   "type":"png"
},
{  
   "file":"images/54_Competition.png",
   "name":"IMAGES_54_Competition_PNG",
   "type":"png"
},
{  
   "file":"images/55_Curiosity.png",
   "name":"IMAGES_55_Curiosity_PNG",
   "type":"png"
},
{  
   "file":"images/56_Time_Pressure.png",
   "name":"IMAGES_56_Time_Pressure_PNG",
   "type":"png"
},
{  
   "file":"images/5_Disruptors.png",
   "name":"IMAGES_5_Disruptors_PNG",
   "type":"png"
},
{  
   "file":"images/6_Free_Spirits.png",
   "name":"IMAGES_6_Free_Spirits_PNG",
   "type":"png"
},
{  
   "file":"images/7_Acheivers.png",
   "name":"IMAGES_7_Acheivers_PNG",
   "type":"png"
},
{  
   "file":"images/8_Player.png",
   "name":"IMAGES_8_Player_PNG",
   "type":"png"
},
{  
   "file":"images/9_Socialisers.png",
   "name":"IMAGES_9_Socialisers_PNG",
   "type":"png"
}
        ]
}